### Post Create Curriculum
POST http://localhost:8080/curriculum
Content-Type: application/json

{
  "nome": "Carlos",
  "idade": "17",
  "tel": "4002-8922",
  "email": "carlosandre116@gmail.com",
  "linkedin": "@jovemcarlosti",
  "github": "jovemcarlosti"
}

### Read All
GET http://localhost:8080/curriculum-infos